export const GOVERNORATES = [
    'Tunis',
    'Ariana',
    'Manouba',
    'Ben Arous',
    'Nabeul',
    'Zaghouan',
    'Bizerte',
    'Kef',
    'Beja',
    'Jendouba',
    'Siliana',
    'Kairouan',
    'Sidi Bouzid',
    'Sousse',
    'Monastir',
    'Mahdia',
    'Sfax',
    'Gafsa',
    'Kasserine',
    'Gabes',
    'Tozeur',
    'Kebili',
    'Medenine',
    'Tataouine',
  ];
  